name: ceemtax_service
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  dartz: ^0.9.1
  dio: ^3.0.10
  get: ^3.11.1
  get_it: ^5.0.1
  get_storage: ^1.3.1
  google_fonts: ^1.1.1
  injectable: 
  retrofit: ^1.3.4+1
  image_picker: ^0.6.7+21
  simple_animations: ^2.4.2
  splashscreen: ^1.3.5
  webview_flutter: ^1.0.7
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.10.11
  injectable_generator: 
  retrofit_generator: 

flutter:
  uses-material-design: true
  assets:
    - images/
